server:
  port: 8889

spring:
  cloud:
    gateway:
#      default-filters:
#        - AuthorizationFilterFactory
      routes:
        - id: images
          predicates:
            - Path=/images/**
          uri: http://localhost:8083/images
          filters:
            - AuthorizationFilterFactory
